[package]
name = "shared"
version = "0.1.0"
authors = ["Alex Martens <alexmgit@protonmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
static_assertions = "^1"

[dependencies.stm32wl-hal]
git = "https://github.com/newAM/stm32wl-hal.git"
rev = "7b471e115566c108025076b828a0a8a64d398876"
features = ["stm32wle5"]
