[package]
name = "shared"
version = "0.1.0"
authors = ["Alex Martens <alexmgit@protonmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
static_assertions = "^1"

[dependencies.stm32wl-hal]
git = "https://github.com/newAM/stm32wl-hal.git"
rev = "1d62a5f085cc483a4bfc8a2a623d0020b743e19c"
features = ["stm32wl5x_cm4"]
