[package]
name = "shared"
version = "0.1.0"
authors = ["Alex Martens <alexmgit@protonmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
static_assertions = "^1"

[dependencies.stm32wl-hal]
git = "https://github.com/newAM/stm32wl-hal.git"
rev = "2d8617921096f77d4d51340814a35efaae94a990"
features = ["stm32wl5x_cm4"]
