on:
  push:
    branches:
      - main
  pull_request:
  # schedule:
  #   - cron: "13 3 * * *"

name: CI

jobs:
  build:
    name: Cargo Build
    runs-on: ubuntu-latest
    env: {"RUSTFLAGS": "-D warnings"}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: thumbv7em-none-eabi
      - run: |
          sudo apt update -y
          sudo apt install -y gcc-arm-none-eabi
      - run: cargo build
